"""Immutable Platform PostgreSQL ACL policy for Alembic 0052.

Revision 0052 widens the existing input-assets table to a mutually exclusive
personal-workspace scope. It adds no table and no new process privilege. The
catalog remains deliberately unqualified until captured on PostgreSQL 16.
"""
from __future__ import annotations

from types import MappingProxyType

from . import database_privileges_v16 as policy_v16


ALEMBIC_HEAD = "0052_personal_input_assets"
MIGRATION_DATABASE_ROLE = policy_v16.MIGRATION_DATABASE_ROLE
DATABASE_ROLE_BY_PROCESS = policy_v16.DATABASE_ROLE_BY_PROCESS
DATABASE_ROLE_COMMENT_BY_PROCESS = policy_v16.DATABASE_ROLE_COMMENT_BY_PROCESS
DATABASE_ROLE_CONNECTION_LIMIT_BY_PROCESS = (
    policy_v16.DATABASE_ROLE_CONNECTION_LIMIT_BY_PROCESS
)
TABLES = policy_v16.TABLES
PRIVILEGES_BY_PROCESS = policy_v16.PRIVILEGES_BY_PROCESS
EXPECTED_TABLE_ACL = policy_v16.EXPECTED_TABLE_ACL
EXPECTED_DATABASE_ACL = policy_v16.EXPECTED_DATABASE_ACL
EXPECTED_SCHEMA_ACL = policy_v16.EXPECTED_SCHEMA_ACL
EXPECTED_DEFAULT_ACL = policy_v16.EXPECTED_DEFAULT_ACL
UNQUALIFIED_CATALOG_SHA256 = "0" * 64
CATALOG_SHA256 = UNQUALIFIED_CATALOG_SHA256
EMPTY_CATALOG_SHA256 = policy_v16.EMPTY_CATALOG_SHA256
MIGRATION_SOURCE_CATALOG_SHA256_BY_HEAD = MappingProxyType(
    {
        policy_v16.ALEMBIC_HEAD: policy_v16.CATALOG_SHA256,
        ALEMBIC_HEAD: CATALOG_SHA256,
    }
)
POSTGRES16_SYSTEM_ACL_BY_SYSTEM_SEMANTIC_SHA256 = (
    policy_v16.POSTGRES16_SYSTEM_ACL_BY_SYSTEM_SEMANTIC_SHA256
)
SYSTEM_ACL_SHA256 = policy_v16.SYSTEM_ACL_SHA256
QUALIFIED_POSTGRES16_SYSTEM_ACL_SHA256 = (
    policy_v16.QUALIFIED_POSTGRES16_SYSTEM_ACL_SHA256
)
