"""Immutable Platform PostgreSQL ACL policy for Alembic 0055.

Revision 0055 adds immutable commercial approval revision columns. It does
not add a table or widen any runtime role, so the v19 table and ACL manifests
remain exact. The catalog stays deliberately unqualified until captured on
PostgreSQL 16.
"""
from __future__ import annotations

from types import MappingProxyType

from . import database_privileges_v19 as policy_v19


ALEMBIC_HEAD = "0055_commercial_plan_revisions"
MIGRATION_DATABASE_ROLE = policy_v19.MIGRATION_DATABASE_ROLE
DATABASE_ROLE_BY_PROCESS = policy_v19.DATABASE_ROLE_BY_PROCESS
DATABASE_ROLE_COMMENT_BY_PROCESS = policy_v19.DATABASE_ROLE_COMMENT_BY_PROCESS
DATABASE_ROLE_CONNECTION_LIMIT_BY_PROCESS = (
    policy_v19.DATABASE_ROLE_CONNECTION_LIMIT_BY_PROCESS
)
TABLES = policy_v19.TABLES
PRIVILEGES_BY_PROCESS = policy_v19.PRIVILEGES_BY_PROCESS
EXPECTED_TABLE_ACL = policy_v19.EXPECTED_TABLE_ACL
EXPECTED_DATABASE_ACL = policy_v19.EXPECTED_DATABASE_ACL
EXPECTED_SCHEMA_ACL = policy_v19.EXPECTED_SCHEMA_ACL
EXPECTED_DEFAULT_ACL = policy_v19.EXPECTED_DEFAULT_ACL
UNQUALIFIED_CATALOG_SHA256 = "0" * 64
CATALOG_SHA256 = UNQUALIFIED_CATALOG_SHA256
EMPTY_CATALOG_SHA256 = policy_v19.EMPTY_CATALOG_SHA256
MIGRATION_SOURCE_CATALOG_SHA256_BY_HEAD = MappingProxyType(
    {
        policy_v19.ALEMBIC_HEAD: policy_v19.CATALOG_SHA256,
        ALEMBIC_HEAD: CATALOG_SHA256,
    }
)
POSTGRES16_SYSTEM_ACL_BY_SYSTEM_SEMANTIC_SHA256 = (
    policy_v19.POSTGRES16_SYSTEM_ACL_BY_SYSTEM_SEMANTIC_SHA256
)
SYSTEM_ACL_SHA256 = policy_v19.SYSTEM_ACL_SHA256
QUALIFIED_POSTGRES16_SYSTEM_ACL_SHA256 = (
    policy_v19.QUALIFIED_POSTGRES16_SYSTEM_ACL_SHA256
)


