"""Immutable Platform PostgreSQL ACL policy for Alembic 0059.

Revision 0059 widens one CHECK on the existing director shot package table. It
adds no table and widens no runtime role: v23 table and ACL manifests remain
exact. No PostgreSQL reference test is runtime qualification; the current
catalog intentionally remains UNQUALIFIED.
"""
from __future__ import annotations

from types import MappingProxyType

from . import database_privileges_v23 as policy_v23


ALEMBIC_HEAD = "0059_director_shot_schema_v2"
MIGRATION_DATABASE_ROLE = policy_v23.MIGRATION_DATABASE_ROLE
DATABASE_ROLE_BY_PROCESS = policy_v23.DATABASE_ROLE_BY_PROCESS
DATABASE_ROLE_COMMENT_BY_PROCESS = policy_v23.DATABASE_ROLE_COMMENT_BY_PROCESS
DATABASE_ROLE_CONNECTION_LIMIT_BY_PROCESS = (
    policy_v23.DATABASE_ROLE_CONNECTION_LIMIT_BY_PROCESS
)
TABLES = policy_v23.TABLES
PRIVILEGES_BY_PROCESS = policy_v23.PRIVILEGES_BY_PROCESS
EXPECTED_TABLE_ACL = policy_v23.EXPECTED_TABLE_ACL
EXPECTED_DATABASE_ACL = policy_v23.EXPECTED_DATABASE_ACL
EXPECTED_SCHEMA_ACL = policy_v23.EXPECTED_SCHEMA_ACL
EXPECTED_DEFAULT_ACL = policy_v23.EXPECTED_DEFAULT_ACL
UNQUALIFIED_CATALOG_SHA256 = "0" * 64
CATALOG_SHA256 = UNQUALIFIED_CATALOG_SHA256
EMPTY_CATALOG_SHA256 = policy_v23.EMPTY_CATALOG_SHA256
MIGRATION_SOURCE_CATALOG_SHA256_BY_HEAD = MappingProxyType(
    {
        policy_v23.ALEMBIC_HEAD: policy_v23.CATALOG_SHA256,
        ALEMBIC_HEAD: CATALOG_SHA256,
    }
)
POSTGRES16_SYSTEM_ACL_BY_SYSTEM_SEMANTIC_SHA256 = (
    policy_v23.POSTGRES16_SYSTEM_ACL_BY_SYSTEM_SEMANTIC_SHA256
)
SYSTEM_ACL_SHA256 = policy_v23.SYSTEM_ACL_SHA256
QUALIFIED_POSTGRES16_SYSTEM_ACL_SHA256 = (
    policy_v23.QUALIFIED_POSTGRES16_SYSTEM_ACL_SHA256
)
