"""Immutable Platform PostgreSQL ACL policy for Alembic 0051.

Revision 0051 adds no tables and widens no process privileges. It adds
provider-account evidence columns and database-enforced immutability only.
The catalog remains deliberately unqualified until captured on PostgreSQL 16.
"""
from __future__ import annotations

from types import MappingProxyType

from . import database_privileges_v15 as policy_v15


ALEMBIC_HEAD = "0051_provider_account_evidence"
MIGRATION_DATABASE_ROLE = policy_v15.MIGRATION_DATABASE_ROLE
DATABASE_ROLE_BY_PROCESS = policy_v15.DATABASE_ROLE_BY_PROCESS
DATABASE_ROLE_COMMENT_BY_PROCESS = policy_v15.DATABASE_ROLE_COMMENT_BY_PROCESS
DATABASE_ROLE_CONNECTION_LIMIT_BY_PROCESS = (
    policy_v15.DATABASE_ROLE_CONNECTION_LIMIT_BY_PROCESS
)
TABLES = policy_v15.TABLES
PRIVILEGES_BY_PROCESS = policy_v15.PRIVILEGES_BY_PROCESS
EXPECTED_TABLE_ACL = policy_v15.EXPECTED_TABLE_ACL
EXPECTED_DATABASE_ACL = policy_v15.EXPECTED_DATABASE_ACL
EXPECTED_SCHEMA_ACL = policy_v15.EXPECTED_SCHEMA_ACL
EXPECTED_DEFAULT_ACL = policy_v15.EXPECTED_DEFAULT_ACL
UNQUALIFIED_CATALOG_SHA256 = "0" * 64
CATALOG_SHA256 = UNQUALIFIED_CATALOG_SHA256
EMPTY_CATALOG_SHA256 = policy_v15.EMPTY_CATALOG_SHA256
MIGRATION_SOURCE_CATALOG_SHA256_BY_HEAD = MappingProxyType(
    {
        policy_v15.ALEMBIC_HEAD: policy_v15.CATALOG_SHA256,
        ALEMBIC_HEAD: CATALOG_SHA256,
    }
)
POSTGRES16_SYSTEM_ACL_BY_SYSTEM_SEMANTIC_SHA256 = (
    policy_v15.POSTGRES16_SYSTEM_ACL_BY_SYSTEM_SEMANTIC_SHA256
)
SYSTEM_ACL_SHA256 = policy_v15.SYSTEM_ACL_SHA256
QUALIFIED_POSTGRES16_SYSTEM_ACL_SHA256 = (
    policy_v15.QUALIFIED_POSTGRES16_SYSTEM_ACL_SHA256
)
