"""Immutable Platform PostgreSQL ACL policy for Alembic 0054.

Revision 0054 adds trusted media metadata columns to ``input_assets``. It does
not add a table or widen any runtime role, so the v18 table and ACL manifests
remain exact. The catalog stays deliberately unqualified until captured on
PostgreSQL 16.
"""
from __future__ import annotations

from types import MappingProxyType

from . import database_privileges_v18 as policy_v18


ALEMBIC_HEAD = "0054_input_asset_media_metadata"
MIGRATION_DATABASE_ROLE = policy_v18.MIGRATION_DATABASE_ROLE
DATABASE_ROLE_BY_PROCESS = policy_v18.DATABASE_ROLE_BY_PROCESS
DATABASE_ROLE_COMMENT_BY_PROCESS = policy_v18.DATABASE_ROLE_COMMENT_BY_PROCESS
DATABASE_ROLE_CONNECTION_LIMIT_BY_PROCESS = (
    policy_v18.DATABASE_ROLE_CONNECTION_LIMIT_BY_PROCESS
)
TABLES = policy_v18.TABLES
PRIVILEGES_BY_PROCESS = policy_v18.PRIVILEGES_BY_PROCESS
EXPECTED_TABLE_ACL = policy_v18.EXPECTED_TABLE_ACL
EXPECTED_DATABASE_ACL = policy_v18.EXPECTED_DATABASE_ACL
EXPECTED_SCHEMA_ACL = policy_v18.EXPECTED_SCHEMA_ACL
EXPECTED_DEFAULT_ACL = policy_v18.EXPECTED_DEFAULT_ACL
UNQUALIFIED_CATALOG_SHA256 = "0" * 64
CATALOG_SHA256 = UNQUALIFIED_CATALOG_SHA256
EMPTY_CATALOG_SHA256 = policy_v18.EMPTY_CATALOG_SHA256
MIGRATION_SOURCE_CATALOG_SHA256_BY_HEAD = MappingProxyType(
    {
        policy_v18.ALEMBIC_HEAD: policy_v18.CATALOG_SHA256,
        ALEMBIC_HEAD: CATALOG_SHA256,
    }
)
POSTGRES16_SYSTEM_ACL_BY_SYSTEM_SEMANTIC_SHA256 = (
    policy_v18.POSTGRES16_SYSTEM_ACL_BY_SYSTEM_SEMANTIC_SHA256
)
SYSTEM_ACL_SHA256 = policy_v18.SYSTEM_ACL_SHA256
QUALIFIED_POSTGRES16_SYSTEM_ACL_SHA256 = (
    policy_v18.QUALIFIED_POSTGRES16_SYSTEM_ACL_SHA256
)
