function demoModeReadiness(modeIds, faceEnabledModes = []) {
  const faceModes = new Set(faceEnabledModes);
  return Object.fromEntries(modeIds.map((mode) => [
    mode,
    {
      default: { ready: true, status: "ready", blockers: [] },
      options: {
        face_enabled: faceModes.has(mode)
          ? { supported: true, ready: true, status: "ready", blockers: [] }
          : { supported: false, ready: false, status: "unsupported", blockers: [] },
      },
    },
  ]));
}

// Keep development-only fixtures behind a compile-time production branch so
// Vite can remove the payload from production bundles.
export const DEVELOPMENT_DEMO_MODEL_RESPONSES = import.meta.env.PROD ? [] : [
  {
    id: "cinemox",
    slug: "cinemox-v2",
    display_name: "CinemoX Pro 2.1",
    pricing_mode: "per_second",
    billing_unit: "POINT",
    billing_version: 2,
    unit_price_points: 30,
    rate: 30,
    mode_readiness: demoModeReadiness(
      ["text_to_video", "image_to_video", "video_to_video"],
      ["text_to_video", "image_to_video", "video_to_video"],
    ),
    effective_capabilities: {
      schema_version: 2,
      modes: {
        text_to_video: {
          input_media_types: ["image", "video", "audio"],
          supports_face: true,
          required_resource_keys: [],
          conditional_required_resource_keys: { face_enabled: ["face.library"] },
          limits: {
            max_prompt_length: 1000,
            max_images: 9,
            max_videos: 3,
            max_audio: 3,
            duration_seconds: [10, 15, 20],
            aspect_ratios: ["16:9", "9:16", "1:1"],
            resolutions: ["720p", "1080p"],
            output_counts: [1],
          },
        },
        image_to_video: {
          input_media_types: ["image", "video", "audio"],
          supports_face: true,
          required_resource_keys: [],
          conditional_required_resource_keys: { face_enabled: ["face.library"] },
          limits: {
            max_prompt_length: 1000,
            max_images: 9,
            max_videos: 3,
            max_audio: 3,
            duration_seconds: [10, 15, 20],
            aspect_ratios: ["16:9", "9:16", "1:1"],
            resolutions: ["720p", "1080p"],
            output_counts: [1],
          },
        },
        video_to_video: {
          input_media_types: ["image", "video", "audio"],
          supports_face: true,
          required_resource_keys: [],
          conditional_required_resource_keys: { face_enabled: ["face.library"] },
          limits: {
            max_prompt_length: 1000,
            max_images: 9,
            max_videos: 3,
            max_audio: 3,
            duration_seconds: [10, 15, 20],
            aspect_ratios: ["16:9", "9:16", "1:1"],
            resolutions: ["720p", "1080p"],
            output_counts: [1],
          },
        },
      },
    },
  },
  {
    id: "rush",
    slug: "rush-video-1.6",
    display_name: "Rush Video 1.6",
    pricing_mode: "per_item",
    billing_unit: "POINT",
    billing_version: 2,
    unit_price_points: 20,
    rate: 20,
    mode_readiness: demoModeReadiness(["text_to_video", "image_to_video"]),
    effective_capabilities: {
      schema_version: 1,
      modes: {
        text_to_video: {
          input_media_types: ["image", "video", "audio"],
          supports_face: false,
          required_resource_keys: [],
          limits: {
            max_prompt_length: 500,
            max_images: 4,
            max_videos: 3,
            max_audio: 3,
            duration_seconds: [5, 10],
            aspect_ratios: ["16:9", "9:16"],
            resolutions: ["720p"],
            output_counts: [1, 2],
          },
        },
        image_to_video: {
          input_media_types: ["image", "video", "audio"],
          supports_face: false,
          required_resource_keys: [],
          limits: {
            max_prompt_length: 500,
            max_images: 4,
            max_videos: 3,
            max_audio: 3,
            duration_seconds: [5, 10],
            aspect_ratios: ["16:9", "9:16"],
            resolutions: ["720p"],
            output_counts: [1, 2],
          },
        },
      },
    },
  },
  {
    id: "frameflow",
    slug: "frameflow-lite",
    display_name: "FrameFlow Lite",
    pricing_mode: "per_item",
    billing_unit: "POINT",
    billing_version: 2,
    unit_price_points: 10,
    rate: 10,
    mode_readiness: demoModeReadiness(["text_to_image"]),
    effective_capabilities: {
      schema_version: 1,
      modes: {
        text_to_image: {
          input_media_types: ["image"],
          supports_face: false,
          required_resource_keys: [],
          limits: {
            max_prompt_length: 500,
            max_images: 1,
            max_videos: 0,
            max_audio: 0,
            duration_seconds: [5],
            aspect_ratios: ["16:9", "1:1"],
            resolutions: ["720p", "1080p"],
            output_counts: [1, 2, 3, 4],
          },
        },
      },
    },
  },
];

export const DEVELOPMENT_DEMO_HISTORY_TASKS = import.meta.env.PROD ? [] : [
  {
    id: "demo-task-complete",
    company_name: "远创电商",
    user_display_name: "陈默",
    user_email: "chenmo@example.cn",
    model_id: "cinemox",
    model_display_name: "CinemoX Pro 2.1",
    status: "succeeded",
    billing_unit: "POINT",
    billing_version: 2,
    request_payload: {
      mode: "image_to_video",
      prompt: "产品防水演示",
      aspect_ratio: "16:9",
      resolution: "1080p",
      duration_seconds: 15,
      output_count: 1,
      assets: [{ media_type: "image" }],
    },
    actual_cost_points: 450,
    artifact_count: 1,
    download_issue_count: 2,
    download_completed_count: 1,
    downloaded: true,
    created_at: "2026-08-01T07:42:00Z",
  },
  {
    id: "demo-task-failed",
    company_name: "远创电商",
    user_display_name: "林瑶",
    model_id: "rush",
    model_display_name: "Rush Video 1.6",
    status: "failed",
    billing_unit: "POINT",
    billing_version: 2,
    request_payload: {
      mode: "text_to_video",
      prompt: "户外使用氛围",
      aspect_ratio: "9:16",
      resolution: "720p",
      duration_seconds: 10,
      output_count: 1,
    },
    quote_points: 180,
    artifact_count: 0,
    created_at: "2026-08-01T08:18:00Z",
  },
];

export const DEVELOPMENT_DEMO_ARTWORKS = import.meta.env.PROD ? [] : [
  {
    artifact_id: "demo-artwork-1",
    task_id: "demo-task-complete",
    asset_id: "demo-video-1",
    output_index: 0,
    media_type: "video",
    content_type: "video/mp4",
    size_bytes: 4372373,
    sha256: "demo-sha256-video",
    model_id: "cinemox",
    company_name: "远创电商",
    created_by_display_name: "陈默",
    model_display_name: "CinemoX Pro 2.1",
    request_payload: DEVELOPMENT_DEMO_HISTORY_TASKS[0].request_payload,
    billing_unit: "POINT",
    billing_version: 2,
    actual_cost_points: 450,
    download_issue_count: 2,
    download_completed_count: 1,
    downloaded: true,
    created_at: "2026-08-01T07:56:00Z",
    preview_url: "/media/speaker-water-hero.png",
  },
  {
    artifact_id: "demo-artwork-2",
    task_id: "demo-task-image",
    asset_id: "demo-image-1",
    output_index: 0,
    media_type: "image",
    content_type: "image/png",
    size_bytes: 8991,
    sha256: "demo-sha256-image",
    model_id: "frameflow",
    company_name: "远创电商",
    created_by_display_name: "张帆",
    model_display_name: "FrameFlow Lite",
    request_payload: {
      mode: "text_to_image",
      prompt: "桌面场景展示",
      aspect_ratio: "1:1",
      resolution: "1080p",
      output_count: 1,
    },
    billing_unit: "POINT",
    billing_version: 2,
    actual_cost_points: 50,
    download_issue_count: 1,
    download_completed_count: 0,
    downloaded: false,
    created_at: "2026-07-31T12:06:00Z",
    preview_url: "/media/scene-indoor.png",
  },
];
