import { buildEntitlementKey } from "./adminConsoleUtils.js";

const companies = [
  { id: "co-yuanchuang", name: "远创电商", plan: "企业版", status: "active" },
  { id: "co-hailan", name: "海岚文旅", plan: "专业版", status: "active" },
  { id: "co-beichen", name: "北辰教育", plan: "企业版", status: "active" },
  { id: "co-lumina", name: "流明内容实验室", plan: "专业版", status: "active" },
  { id: "co-xingzhou", name: "星舟品牌", plan: "基础版", status: "suspended" },
];

const entitlementProducts = [
  { id: "model-minimax-h3", name: "MiniMax H3", kind: "model", status: "active" },
  { id: "model-kling-21", name: "Kling 2.1", kind: "model", status: "active" },
  { id: "feature-video-replica", name: "视频复刻", kind: "feature", status: "active" },
  { id: "feature-auto-publish", name: "自动发布", kind: "feature", status: "active" },
  { id: "agent-copywriter", name: "带货文案智能体", kind: "agent", status: "active" },
  { id: "api-generations", name: "生成 API", kind: "external_api", status: "active" },
  { id: "api-callback", name: "任务回调 API", kind: "external_api", status: "active" },
];

const grant = (companyId, productId, state, extra = {}) => [
  buildEntitlementKey(companyId, productId),
  {
    companyId,
    productId,
    state,
    priceCents: extra.priceCents ?? null,
    quota: extra.quota ?? null,
    concurrency: extra.concurrency ?? null,
    effectiveAt: extra.effectiveAt ?? "2026-08-01T00:00",
    expiresAt: extra.expiresAt ?? "",
    capabilityLimit: extra.capabilityLimit ?? "",
  },
];

const entitlementGrants = Object.fromEntries([
  grant("co-yuanchuang", "model-minimax-h3", "enabled", { priceCents: 480, quota: 30000, concurrency: 24 }),
  grant("co-yuanchuang", "model-kling-21", "enabled", { priceCents: 650, quota: 18000, concurrency: 12 }),
  grant("co-yuanchuang", "feature-video-replica", "enabled"),
  grant("co-yuanchuang", "feature-auto-publish", "enabled", { concurrency: 8 }),
  grant("co-yuanchuang", "agent-copywriter", "enabled", { quota: 5000 }),
  grant("co-yuanchuang", "api-generations", "enabled", { quota: 120000, concurrency: 30 }),
  grant("co-yuanchuang", "api-callback", "enabled"),
  grant("co-hailan", "model-minimax-h3", "enabled", { priceCents: 520, quota: 12000, concurrency: 8 }),
  grant("co-hailan", "model-kling-21", "expiring", { priceCents: 720, quota: 8000, concurrency: 6, expiresAt: "2026-08-15T23:59" }),
  grant("co-hailan", "feature-video-replica", "disabled"),
  grant("co-hailan", "feature-auto-publish", "enabled", { concurrency: 3 }),
  grant("co-hailan", "agent-copywriter", "enabled", { quota: 1200 }),
  grant("co-hailan", "api-generations", "enabled", { quota: 30000, concurrency: 10 }),
  grant("co-hailan", "api-callback", "enabled"),
  grant("co-beichen", "model-minimax-h3", "enabled", { priceCents: 500, quota: 10000, concurrency: 8 }),
  grant("co-beichen", "model-kling-21", "disabled"),
  grant("co-beichen", "feature-video-replica", "enabled"),
  grant("co-beichen", "feature-auto-publish", "unconfigured"),
  grant("co-beichen", "agent-copywriter", "enabled", { quota: 1800 }),
  grant("co-beichen", "api-generations", "disabled"),
  grant("co-beichen", "api-callback", "unconfigured"),
  grant("co-lumina", "model-minimax-h3", "enabled", { priceCents: 600, quota: 6000, concurrency: 5 }),
  grant("co-lumina", "model-kling-21", "enabled", { priceCents: 780, quota: 6000, concurrency: 5 }),
  grant("co-lumina", "feature-video-replica", "enabled"),
  grant("co-lumina", "feature-auto-publish", "expired", { expiresAt: "2026-08-01T00:00" }),
  grant("co-lumina", "agent-copywriter", "enabled", { quota: 850 }),
  grant("co-lumina", "api-generations", "enabled", { quota: 20000, concurrency: 8 }),
  grant("co-lumina", "api-callback", "enabled"),
  grant("co-xingzhou", "model-minimax-h3", "disabled"),
  grant("co-xingzhou", "model-kling-21", "disabled"),
  grant("co-xingzhou", "feature-video-replica", "disabled"),
  grant("co-xingzhou", "feature-auto-publish", "disabled"),
  grant("co-xingzhou", "agent-copywriter", "disabled"),
  grant("co-xingzhou", "api-generations", "disabled"),
  grant("co-xingzhou", "api-callback", "disabled"),
]);

export const DEMO_ADMIN_OPERATIONS_DATA = {
  summary: {
    pending: 12,
    alertBacklog: 3,
    unreconciledCosts: 7,
    lastRefreshed: "2026-08-07T12:29:43+08:00",
    environment: "production",
  },
  taskFlow: [
    { key: "submitted", label: "提交", total: 128763, rate: 100, delta: 12.4, dropoffLabel: "放弃 / 失败", dropoff: 7824, dropoffRate: 6.1 },
    { key: "queued", label: "排队", total: 25614, rate: 19.9, dropoffLabel: "放弃 / 超时", dropoff: 8722, dropoffRate: 34.0 },
    { key: "generating", label: "生成中", total: 16892, rate: 66.0, dropoffLabel: "转存失败", dropoff: 1160, dropoffRate: 6.9 },
    { key: "transferring", label: "产物转存", total: 15732, rate: 93.1, dropoffLabel: "回调失败", dropoff: 609, dropoffRate: 3.9 },
    { key: "reconciled", label: "回调完成", total: 15123, rate: 96.1 },
  ],
  timings: [
    { key: "queue", label: "排队耗时", p50: 18, p95: 102 },
    { key: "generation", label: "生成耗时", p50: 134, p95: 448 },
    { key: "transfer", label: "转存耗时", p50: 36, p95: 131 },
    { key: "callback", label: "回调耗时", p50: 12, p95: 48 },
  ],
  trends: [
    { time: "12:00", submitted: 61000, generating: 40000, completed: 24500, failed: 6100 },
    { time: "14:00", submitted: 75000, generating: 45000, completed: 28000, failed: 7000 },
    { time: "16:00", submitted: 72000, generating: 44000, completed: 27000, failed: 6700 },
    { time: "18:00", submitted: 85000, generating: 54000, completed: 33000, failed: 8300 },
    { time: "20:00", submitted: 76000, generating: 47000, completed: 30000, failed: 6900 },
    { time: "22:00", submitted: 72000, generating: 44000, completed: 27000, failed: 6500 },
    { time: "00:00", submitted: 79000, generating: 50000, completed: 31000, failed: 8000 },
    { time: "02:00", submitted: 76000, generating: 46000, completed: 29000, failed: 6800 },
    { time: "04:00", submitted: 64000, generating: 37000, completed: 23000, failed: 5900 },
    { time: "06:00", submitted: 76000, generating: 44000, completed: 27000, failed: 6900 },
    { time: "08:00", submitted: 78000, generating: 46000, completed: 28000, failed: 6700 },
    { time: "10:00", submitted: 80000, generating: 47000, completed: 29000, failed: 7000 },
    { time: "12:00 ", submitted: 73000, generating: 42000, completed: 26000, failed: 6200 },
  ],
  failureTrends: [
    { time: "12:00", modelError: 1900, resourceShortage: 1500, timeout: 1200, contentReview: 980, transferFailure: 620, other: 450 },
    { time: "16:00", modelError: 2200, resourceShortage: 1800, timeout: 1250, contentReview: 1120, transferFailure: 700, other: 500 },
    { time: "20:00", modelError: 2050, resourceShortage: 1900, timeout: 1320, contentReview: 1080, transferFailure: 640, other: 450 },
    { time: "00:00", modelError: 2450, resourceShortage: 1940, timeout: 1440, contentReview: 1200, transferFailure: 760, other: 500 },
    { time: "04:00", modelError: 2100, resourceShortage: 1750, timeout: 1100, contentReview: 1020, transferFailure: 600, other: 430 },
    { time: "08:00", modelError: 2350, resourceShortage: 2100, timeout: 1280, contentReview: 1150, transferFailure: 680, other: 470 },
    { time: "12:00 ", modelError: 2500, resourceShortage: 2200, timeout: 1300, contentReview: 1200, transferFailure: 700, other: 500 },
  ],
  failureReasons: [
    { key: "modelError", label: "模型错误", count: 2184, share: 27.9, change: 8.6 },
    { key: "resourceShortage", label: "资源不足", count: 1962, share: 25.1, change: 6.2 },
    { key: "timeout", label: "超时", count: 1588, share: 20.3, change: -3.1 },
    { key: "contentReview", label: "内容审核", count: 1112, share: 14.2, change: -1.8 },
    { key: "transferFailure", label: "转存失败", count: 572, share: 7.3, change: 2.4 },
    { key: "other", label: "其他", count: 420, share: 5.2, change: -0.7 },
  ],
  latencyDistribution: [
    { seconds: 0, cumulative: 0 },
    { seconds: 1, cumulative: 4 },
    { seconds: 2, cumulative: 12 },
    { seconds: 3, cumulative: 24 },
    { seconds: 4, cumulative: 38 },
    { seconds: 5, cumulative: 53 },
    { seconds: 6, cumulative: 68 },
    { seconds: 7, cumulative: 80 },
    { seconds: 8, cumulative: 89 },
    { seconds: 9, cumulative: 94 },
    { seconds: 10, cumulative: 97 },
    { seconds: 12, cumulative: 99 },
    { seconds: 14, cumulative: 100 },
  ],
  exceptions: [
    { id: "ex-relay-map", priority: "P1", kind: "relay_unmapped", title: "Relay 模型未映射", description: "存在 18 个未映射 Relay 模型", duration: "2h 37m", owner: "张伟", status: "investigating", occurredAt: "2026-08-07T09:52:00+08:00", nextAction: "核对 Relay 模型别名并完成目录审批。" },
    { id: "ex-channel-drop", priority: "P1", kind: "channel_success_drop", title: "渠道成功率骤降", description: "第三方 API 渠道成功率低于 85% 持续 30 分钟", duration: "1h 15m", owner: "李娜", status: "investigating", occurredAt: "2026-08-07T11:14:00+08:00", nextAction: "确认是否降权并检查备用渠道容量。" },
    { id: "ex-submission-unknown", category: "RELAY_SUBMISSION_UNKNOWN", priority: "P2", kind: "relay_submission_unknown", title: "Relay submission_unknown 待核对", description: "存在 Provider 响应丢失的未知提交", duration: "58m", owner: "王强", status: "open", occurredAt: "2026-08-07T11:31:00+08:00", nextAction: "进入 Relay 人工对账列表，重新读取 fencing 详情后逐条核实；禁止自动或跨渠道重试。" },
    { id: "ex-obs", priority: "P2", kind: "obs_transfer", title: "OBS 转存失败", description: "转存失败率超过 5%，持续 20 分钟", duration: "47m", owner: "陈晨", status: "open", occurredAt: "2026-08-07T11:42:00+08:00", nextAction: "检查 OBS 配额、网络和对象校验失败原因。" },
    { id: "ex-oauth", priority: "P3", kind: "oauth_expiry", title: "OAuth 即将过期", description: "3 个账号将在 24 小时内到期", duration: "3h 05m", owner: "系统", status: "open", occurredAt: "2026-08-07T09:24:00+08:00", nextAction: "通知企业重新授权，并阻止到期后的新发布。" },
    { id: "ex-reserve", priority: "P3", kind: "reservation", title: "预留余额长期未释放", description: "12 个预留项超过 7 天未释放", duration: "5h 42m", owner: "财务组", status: "open", occurredAt: "2026-08-07T06:47:00+08:00", nextAction: "核对任务终态并执行补偿释放。" },
  ],
  reliability: [
    { id: "rel-1", model: "MiniMax H3", channel: "官方-MiniMax", channelClass: "官方渠道", calls: 42681, successRate: 98.42, p95: 6.21, rateLimited: 0.2, failover: "未启用", missingCostCents: 0, status: "healthy" },
    { id: "rel-2", model: "Kling 2.1", channel: "第三方-火山引擎", channelClass: "第三方 API", calls: 24157, successRate: 95.18, p95: 8.73, rateLimited: 1.8, failover: "备用就绪", missingCostCents: 18640, status: "warning" },
    { id: "rel-3", model: "Runway Gen-3", channel: "第三方-硅基流动", channelClass: "第三方 API", calls: 18932, successRate: 93.27, p95: 9.41, rateLimited: 2.6, failover: "未启用", missingCostCents: 51230, status: "critical" },
    { id: "rel-4", model: "Stable Diffusion XL", channel: "逆向-SDXLProxy", channelClass: "逆向渠道", calls: 12648, successRate: 88.03, p95: 11.82, rateLimited: 6.3, failover: "自动切换中", missingCostCents: 102450, status: "critical" },
    { id: "rel-5", model: "PixVerse V6", channel: "官方-PixVerse", channelClass: "官方渠道", calls: 9815, successRate: 99.21, p95: 5.43, rateLimited: 0.1, failover: "未启用", missingCostCents: 0, status: "healthy" },
  ],
  business: {
    metrics: [
      { key: "recharge", label: "充值现金流", valueCents: 416820000, change: 12.8 },
      { key: "revenue", label: "结算收入", valueCents: 312640000, change: 8.4 },
      { key: "cost", label: "渠道成本", valueCents: 174390000, change: 6.2 },
      { key: "grossProfit", label: "毛利", valueCents: 138250000, change: 11.3 },
      { key: "grossMargin", label: "毛利率", valuePercent: 44.22, change: 1.2 },
    ],
    trend: [
      { date: "08-01", recharge: 520000, revenue: 382000, cost: 208000, grossProfit: 174000 },
      { date: "08-02", recharge: 610000, revenue: 426000, cost: 242000, grossProfit: 184000 },
      { date: "08-03", recharge: 480000, revenue: 401000, cost: 225000, grossProfit: 176000 },
      { date: "08-04", recharge: 720000, revenue: 462000, cost: 254000, grossProfit: 208000 },
      { date: "08-05", recharge: 680000, revenue: 493000, cost: 268000, grossProfit: 225000 },
      { date: "08-06", recharge: 530000, revenue: 445000, cost: 250000, grossProfit: 195000 },
      { date: "08-07", recharge: 630000, revenue: 517000, cost: 297000, grossProfit: 220000 },
    ],
    companyRanking: [
      { id: "co-yuanchuang", name: "远创电商", revenueCents: 98260000, taskCount: 42813, successRate: 98.1, balanceCents: 8870000 },
      { id: "co-hailan", name: "海岚文旅", revenueCents: 72680000, taskCount: 31242, successRate: 96.7, balanceCents: 5230000 },
      { id: "co-beichen", name: "北辰教育", revenueCents: 58420000, taskCount: 22691, successRate: 94.2, balanceCents: 2810000 },
      { id: "co-lumina", name: "流明内容实验室", revenueCents: 43930000, taskCount: 18332, successRate: 97.3, balanceCents: 1460000 },
    ],
  },
  modelProfitability: [
    { id: "model-minimax-h3", model: "MiniMax H3", calls: 42681, revenueCents: 128043000, costCents: 61941000, grossProfitCents: 66049000, grossMargin: 51.58, successRate: 98.42, avgSeconds: 5.28, missingCostRate: 0 },
    { id: "model-kling-21", model: "Kling 2.1", calls: 24157, revenueCents: 93608000, costCents: 52823000, grossProfitCents: 40785000, grossMargin: 43.57, successRate: 95.18, avgSeconds: 7.11, missingCostRate: 1.7 },
    { id: "model-runway-gen3", model: "Runway Gen-3", calls: 18932, revenueCents: 61478000, costCents: 43108000, grossProfitCents: 18370000, grossMargin: 29.88, successRate: 93.27, avgSeconds: 8.64, missingCostRate: 4.8 },
    { id: "model-sdxl", model: "Stable Diffusion XL", calls: 12648, revenueCents: 29511000, costCents: 16518000, grossProfitCents: 12993000, grossMargin: 44.03, successRate: 88.03, avgSeconds: 9.52, missingCostRate: 8.2 },
    { id: "model-pixverse-v6", model: "PixVerse V6", calls: 9815, revenueCents: 31986000, costCents: 18127000, grossProfitCents: 13859000, grossMargin: 43.33, successRate: 99.21, avgSeconds: 4.76, missingCostRate: 0 },
  ],
  companyHealth: [
    { id: "co-yuanchuang", name: "远创电商", risk: "healthy", balanceCents: 8870000, daysInactive: 0, consumptionChange: 18.2, reservationAgeHours: 1.2, failureRate: 1.9, entitlementsExpiring: 0, reasons: [] },
    { id: "co-hailan", name: "海岚文旅", risk: "warning", balanceCents: 5230000, daysInactive: 0, consumptionChange: 42.8, reservationAgeHours: 4.6, failureRate: 3.3, entitlementsExpiring: 1, reasons: ["消费环比突增", "1 项权益 7 日内到期"] },
    { id: "co-beichen", name: "北辰教育", risk: "critical", balanceCents: 281000, daysInactive: 0, consumptionChange: -8.1, reservationAgeHours: 176, failureRate: 11.6, entitlementsExpiring: 0, reasons: ["余额不足", "预留余额超 7 天", "失败率过高"] },
    { id: "co-lumina", name: "流明内容实验室", risk: "warning", balanceCents: 1460000, daysInactive: 16, consumptionChange: -62.7, reservationAgeHours: 0, failureRate: 2.7, entitlementsExpiring: 1, reasons: ["超过 14 天未活跃", "自动发布权益已过期"] },
    { id: "co-xingzhou", name: "星舟品牌", risk: "inactive", balanceCents: 0, daysInactive: 42, consumptionChange: -100, reservationAgeHours: 0, failureRate: 0, entitlementsExpiring: 0, reasons: ["企业已停用"] },
  ],
  channels: [
    { id: "ch-minimax-official", name: "官方-MiniMax", channelClass: "official", successRate: 98.42, activeAccounts: 6, coolingAccounts: 0, invalidAccounts: 0, rateLimits: 8, failovers: 0, alertBacklog: 0, status: "healthy" },
    { id: "ch-volcano-third", name: "第三方-火山引擎", channelClass: "third_party_api", successRate: 95.18, activeAccounts: 12, coolingAccounts: 2, invalidAccounts: 0, rateLimits: 74, failovers: 14, alertBacklog: 1, status: "warning" },
    { id: "ch-silicon-third", name: "第三方-硅基流动", channelClass: "third_party_api", successRate: 93.27, activeAccounts: 8, coolingAccounts: 3, invalidAccounts: 1, rateLimits: 106, failovers: 32, alertBacklog: 1, status: "critical" },
    { id: "ch-sdxl-reverse", name: "逆向-SDXLProxy", channelClass: "reverse", successRate: 88.03, activeAccounts: 18, coolingAccounts: 7, invalidAccounts: 5, rateLimits: 269, failovers: 88, alertBacklog: 3, status: "critical" },
    { id: "ch-pixverse-official", name: "官方-PixVerse", channelClass: "official", successRate: 99.21, activeAccounts: 4, coolingAccounts: 0, invalidAccounts: 0, rateLimits: 3, failovers: 0, alertBacklog: 0, status: "healthy" },
  ],
  relayChannels: [
    { id: 17, name: "视频主通道", type: 1, typeLabel: "OpenAI", status: "enabled", configuredModels: ["kling-video-v2.1", "pixverse-video-v6"], modelCount: 2, testModel: "kling-video-v2.1", testSupported: true, weight: 100, priority: 10, autoBan: true, tag: "video-primary", createdAt: "2026-07-18T09:15:00+08:00", lastTestedAt: "2026-08-07T14:31:42+08:00", responseTimeMs: 413, credentialConfigured: true, revision: `sha256:${"d".repeat(64)}` },
    { id: 23, name: "原生视频补充通道", type: 14, typeLabel: "Kling Native", status: "manually_disabled", configuredModels: ["kling-v2.1"], modelCount: 1, testModel: null, testSupported: false, weight: 50, priority: 20, autoBan: true, tag: "video-fallback", createdAt: "2026-07-23T16:40:00+08:00", lastTestedAt: null, responseTimeMs: null, credentialConfigured: true, revision: `sha256:${"e".repeat(64)}` },
    { id: 31, name: "待补凭据通道", type: 3, typeLabel: "Azure OpenAI", status: "auto_disabled", configuredModels: ["video-preview"], modelCount: 1, testModel: "video-preview", testSupported: true, weight: 10, priority: 50, autoBan: true, tag: "credential-review", createdAt: "2026-08-02T10:00:00+08:00", lastTestedAt: null, responseTimeMs: null, credentialConfigured: false, revision: `sha256:${"f".repeat(64)}` },
  ],
  relayChannelSourceStatus: "available",
  relayChannelTotal: 3,
  relayUnknownSubmissions: [
    {
      jobId: "91c5cd71-bde2-4cf9-b6ed-b264b0841f51",
      tenantId: "51bdf7c4-93a6-4b7c-a4a1-03f616a10f30",
      clientReferenceId: "demo-platform-task-2086",
      model: "kling-video-v2.1",
      mode: "image_to_video",
      status: "reconciliation_required",
      providerRouteId: 208,
      providerRouteKey: "kling-official-prod-01",
      providerName: "Kling Official",
      providerAccountId: "demo-kling-account-07",
      providerChannelId: 31,
      providerKeyIndex: 0,
      providerChannelClass: "official",
      providerUpstreamModel: "kling-v2-1-master",
      providerSubmissionAttempt: 1,
      unknownAt: "2026-08-07T11:31:00+08:00",
      reconciliationToken: `sha256:${"a".repeat(64)}`,
      errorCode: "PROVIDER_RESPONSE_LOSS",
      errorMessage: "Provider POST completed but its response was lost",
      createdAt: "2026-08-07T11:30:42+08:00",
      updatedAt: "2026-08-07T11:31:00+08:00",
    },
  ],
  relayUnknownSubmissionPage: 1,
  relayUnknownSubmissionPageSize: 100,
  relayUnknownSubmissionTotal: 1,
  relayUnknownSubmissionSourceStatus: "available",
  publishingExceptions: [
    { id: "pub-unknown-01", priority: "P1", kind: "submission_unknown", title: "抖音发布结果未知", description: "远创电商 · 夏季新品推广", account: "远创电商旗舰店", provider: "douyin", occurredAt: "2026-08-07T11:14:00+08:00", status: "open" },
    { id: "pub-expired-02", priority: "P2", kind: "oauth_expiry", title: "发布账号授权即将到期", description: "海岚文旅 · 小红书矩阵号", account: "海岚旅行日记", provider: "xiaohongshu", occurredAt: "2026-08-07T10:25:00+08:00", status: "open" },
    { id: "pub-failed-03", priority: "P2", kind: "publish_failed", title: "发布失败待人工处理", description: "北辰教育 · 暑期公开课", account: "北辰教育官方", provider: "weixin_channels", occurredAt: "2026-08-07T09:42:00+08:00", status: "investigating" },
  ],
  assetExceptions: [
    { id: "asset-obs-01", priority: "P1", kind: "obs_transfer", title: "产物转存校验失败", description: "对象摘要与提供方元数据不一致", company: "流明内容实验室", occurredAt: "2026-08-07T11:48:00+08:00", status: "open" },
    { id: "asset-download-02", priority: "P2", kind: "download_audit", title: "下载完成事件缺失", description: "已签发下载 URL，但没有可信完成记录", company: "远创电商", occurredAt: "2026-08-07T10:54:00+08:00", status: "open" },
    { id: "asset-storage-03", priority: "P3", kind: "storage_binding", title: "存储绑定即将过期", description: "华为云 OBS 临时委托将在 36 小时后过期", company: "平台存储", occurredAt: "2026-08-07T08:16:00+08:00", status: "investigating" },
  ],
  companies,
  entitlementProducts,
  entitlementTemplates: [
    { id: "starter", name: "基础创作套餐", productIds: ["model-minimax-h3", "feature-video-replica"] },
    { id: "professional", name: "专业运营套餐", productIds: ["model-minimax-h3", "model-kling-21", "feature-video-replica", "feature-auto-publish", "agent-copywriter"] },
    { id: "enterprise", name: "企业全能力套餐", productIds: entitlementProducts.map((item) => item.id) },
  ],
  entitlementCoverage: [
    { id: "model-minimax-h3", name: "MiniMax H3", kind: "model", active: true, totalCompanies: 5, configuredCompanies: 5, enabledCompanies: 4, disabledCompanies: 1, scheduledCompanies: 0, expiredCompanies: 0, coverageRate: 80 },
    { id: "model-kling-21", name: "Kling 2.1", kind: "model", active: true, totalCompanies: 5, configuredCompanies: 5, enabledCompanies: 3, disabledCompanies: 2, scheduledCompanies: 0, expiredCompanies: 0, coverageRate: 60 },
    { id: "feature-video-replica", name: "视频复刻", kind: "feature", active: true, totalCompanies: 5, configuredCompanies: 5, enabledCompanies: 3, disabledCompanies: 2, scheduledCompanies: 0, expiredCompanies: 0, coverageRate: 60 },
    { id: "feature-auto-publish", name: "自动发布", kind: "feature", active: true, totalCompanies: 5, configuredCompanies: 4, enabledCompanies: 2, disabledCompanies: 1, scheduledCompanies: 0, expiredCompanies: 1, coverageRate: 40 },
    { id: "agent-copywriter", name: "带货文案智能体", kind: "agent", active: true, totalCompanies: 5, configuredCompanies: 5, enabledCompanies: 4, disabledCompanies: 1, scheduledCompanies: 0, expiredCompanies: 0, coverageRate: 80 },
    { id: "api-generations", name: "生成 API", kind: "external_api", active: true, totalCompanies: 5, configuredCompanies: 5, enabledCompanies: 3, disabledCompanies: 2, scheduledCompanies: 0, expiredCompanies: 0, coverageRate: 60 },
    { id: "api-callback", name: "任务回调 API", kind: "external_api", active: true, totalCompanies: 5, configuredCompanies: 4, enabledCompanies: 3, disabledCompanies: 1, scheduledCompanies: 0, expiredCompanies: 0, coverageRate: 60 },
  ],
  entitlementGrants,
  auditEvents: [
    { id: "audit-1", occurredAt: "2026-08-07T12:12:43+08:00", actorName: "周宁", actorId: "admin-owner", actionLabel: "批量开通企业权益", action: "entitlement.batch.enable", targetLabel: "远创电商等 3 家企业", reason: "新签企业版套餐，自 8 月账期生效", result: "success", before: { enabledCompanies: 1, quota: 20000, expiresAt: null }, after: { enabledCompanies: 3, quota: 60000, expiresAt: "2027-07-31" }, rollbackHint: "按审计记录创建反向批次" },
    { id: "audit-2", occurredAt: "2026-08-07T11:46:09+08:00", actorName: "李娜", actorId: "admin-ops", actionLabel: "调整模型价格", action: "model.price.update", targetLabel: "海岚文旅 · Kling 2.1", reason: "同步 2026-Q3 合同价格", result: "success", before: { unitPriceCents: 760, pricingMode: "per_second" }, after: { unitPriceCents: 720, pricingMode: "per_second" }, rollbackHint: "重新提交旧价格并填写关联审计号" },
    { id: "audit-3", occurredAt: "2026-08-07T10:38:18+08:00", actorName: "王强", actorId: "admin-support", actionLabel: "停用发布账号", action: "publishing.connection.disable", targetLabel: "海岚旅行日记", reason: "企业确认账号已停用", result: "success", before: { status: "active", queuedJobs: 4 }, after: { status: "disabled", queuedJobs: 0 }, rollbackHint: "账号需重新完成 OAuth，不能直接回滚" },
    { id: "audit-4", occurredAt: "2026-08-07T09:22:56+08:00", actorName: "陈晨", actorId: "admin-finance", actionLabel: "补录渠道成本", action: "channel.cost.create", targetLabel: "第三方-硅基流动", reason: "补录供应商 8 月 6 日对账单", result: "success", before: { amountCents: 0, reconciliation: "incomplete" }, after: { amountCents: 51230, reconciliation: "complete" }, rollbackHint: "追加负数调整项，不删除原成本记录" },
  ],
  adminPermissionCatalog: [
    { key: "platform.dashboard.read", label: "查看经营驾驶舱", group: "经营分析" },
    { key: "platform.tasks.read", label: "查看任务运营", group: "任务运营" },
    { key: "platform.entitlements.manage", label: "管理企业权益", group: "企业权益" },
    { key: "platform.companies.manage", label: "管理企业状态", group: "企业管理" },
    { key: "platform.billing.read", label: "查看平台账务", group: "财务" },
    { key: "platform.billing.manage", label: "充值与成本录入", group: "财务" },
    { key: "platform.channels.read", label: "查看渠道健康", group: "渠道" },
    { key: "platform.publishing.read", label: "查看发布异常", group: "发布" },
    { key: "platform.audit.read", label: "查看操作审计", group: "安全审计" },
    { key: "platform.admins.manage", label: "管理平台管理员", group: "安全审计" },
  ],
  platformAdmins: [
    { id: "admin-owner", name: "周宁", email: "owner@verse.example", roleLabel: "平台所有者", owner: true, status: "active", lastActiveAt: "2026-08-07T12:28:00+08:00", permissions: ["*"] },
    { id: "admin-ops", name: "李娜", email: "ops@verse.example", roleLabel: "运营管理员", owner: false, status: "active", lastActiveAt: "2026-08-07T11:51:00+08:00", permissions: ["platform.dashboard.read", "platform.tasks.read", "platform.entitlements.manage", "platform.companies.manage", "platform.channels.read", "platform.publishing.read", "platform.audit.read"] },
    { id: "admin-finance", name: "陈晨", email: "finance@verse.example", roleLabel: "财务管理员", owner: false, status: "active", lastActiveAt: "2026-08-07T10:06:00+08:00", permissions: ["platform.dashboard.read", "platform.billing.read", "platform.billing.manage", "platform.audit.read"] },
    { id: "admin-support", name: "王强", email: "support@verse.example", roleLabel: "支持管理员", owner: false, status: "active", lastActiveAt: "2026-08-07T09:42:00+08:00", permissions: ["platform.dashboard.read", "platform.tasks.read", "platform.publishing.read", "platform.audit.read"] },
  ],
};

export default DEMO_ADMIN_OPERATIONS_DATA;
